name: hello

on:
    push:
        branches: ['main']

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Saludar
              run: echo "Hola desde gh"

            - name: ver fecha
              run: date

            - name: Ver files
              run: ls -al
