name: events!. asd

on:
    issues:
        types: [opened, reopened]

jobs:
    inspect-things:
        runs-on: ubuntu-22.04
        permissions:
            issues: write
        steps:
            - name: Inspección
              run: |
                  echo "Event: ${{github.event_name}}"
                  echo "Issue: ${{github.event.issue.number}}"
                  echo "Issue comment: ${{github.event.issue.body}}"
                  echo "Issue title: ${{github.event.issue.title}}"

            - name: Comentario automatico
              env:
                  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  ISSUE_NUMBER: ${{github.event.issue.number}}
                  REPO: ${{github.repository}}
              run: |
                  gh issue comment "$ISSUE_NUMBER" --body "Gracias por tu aporte." --repo "$REPO"
